---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# quacker

<!-- badges: start -->
<!-- badges: end -->

The goal of quacker is to improve the ease and consistency of quality analysis and quality control (QA/QC) methods used in data science.

quacker is still in active development.

## Installation

You can install the development version of quacker like so:

``` r
# install.packages("pak")
pak::pak("B-Nilson/quacker")
```

## Example

Here is how you can use quaker to QA/QC timeseries data:

```{r example}
library(quacker)

example_ts <- data.frame(
  date = seq(
    lubridate::ymd_h("2022-01-01 00"),
    lubridate::ymd_h("2022-01-01 23"),
    by = "1 hour"
  ),
  value_a = 1:24,
  value_b = rep(1:6, each = 3) |> c(100, 0, 0, 0, 0, NA)
)

flagged_data <- qaqc_timeseries(
  ts_data = example_ts,
  date_col = "date",
  value_cols = c("value_a", "value_b"),
  allowed_range = c(0, 80),
  allowed_steps = list("1 hours" = 5, "3 hours" = 100),
  allowed_repeats = 3,
  precision = 1
)

flagged_data |>
  dplyr::select(-"date") |> # for cleaner printing
  print(n = 24)

flagged_data |> 
  plot_timeseries_qaqc()
```
